module.exports = async (app) => {
    global.tabelFieldMap = {
        receiptFields: {
            status: 1,
            customerId: 1,
            titleId: 1,
            carrierId: 1,
            containerNo: 1,
            containerSize: 1,
            trailerNo:1,
            trailerSize:1,
            sealNo: 1,
            referenceNo: 1,
            poNo: 1,
            bolNo: 1,
            eta: 1,
            appointmentTime: 1,
            inYardTime: 1,
            devannedTime: 1,
            closeTime: 1,
            createdWhen: 1,
            source: 1,
            isTransload: 1,
            receiveType: 1,
            receiptType: 1,
            transferTypeFromCrossDockDate: 1
        },
        itemSpecFields: {
            name: 1,
            desc: 1,
            customerId: 1,
            brandId: 1,
            groupId: 1,
            shortDescription: 1,
            upcCode: 1,
            upcCodeCase: 1,
            hasSerialNumber: 1,
            bundle: 1,
            grade: 1
        },
        orderFields: {
            customerId: 1,
            carrierId: 1,
            retailerId: 1,
            proNo: 1,
            referenceNo: 1,
            bolNo: 1,
            loadNo: 1,
            containerSize: 1,
            poNo: 1,
            soNos: 1,
            status: 1,
            mabd: 1,
            appointmentTime: 1,
            canceledDate: 1,
            scheduleDate: 1,
            shippedTime: 1,
            inYardTime: 1,
            shipToAddress: 1,
            source: 1,
            totalPallets: 1,
            orderType: 1,
            orderTypeCode: 1,
            isTransload: 1,
            createdWhen: 1
        },
        inventoryFields: "itemSpecId,type,unitId,qty,weight,pickRoundNo,weightUnit,status,lpId,supplierId,customerId,titleId,pickTaskId,receiptId,receivedWhen,orderId,lotNo,createdWhen,originalReceiveLPId",
        materialLineFields: {
            receiptId: 1,
            orderId: 1,
            itemSpecId: 1,
            unitId: 1,
            qty: 1,
            customerId: 1,
            titleId: 1,
            lpConfigurationId: 1
        },
        orderItemLineFields: {
            orderId: 1,
            itemSpecId: 1,
            unitId: 1,
            lotNo: 1,
            qty: 1,
            shippedQty: 1,
            palletQty: 1,
            adjustedPalletQty:1,
            titleId: 1,
            supplierId: 1,
            lpConfigurationId: 1
        }
    };
}